name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS Lambda
      uses: aws-actions/lambda-deploy-function@v1
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: AKIAR6IRPXJJHTWFFAHB
        AWS_SECRET_ACCESS_KEY: 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
      with:
        function-name: my-lambda-function
        zip-file: dist/lambda.zip
